presubmits:
  gardener/gardener-extension-provider-equinix-metal:
  - name: pull-gardener-extension-provider-equinix-metal-verify-image-build
    cluster: gardener-prow-build
    always_run: true
    annotations:
      description: Verify Gardener extension registry-cache image build on pull requests
    decorate: true
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:v1.23.2
        command:
        - /kaniko/executor
        args:
        - --context=/home/prow/go/src/github.com/gardener/gardener-extension-provider-equinix-metal
        - --dockerfile=Dockerfile
        - --no-push
        - --registry-mirror=registry-docker-io.kube-system.svc.cluster.local:5000
        - --insecure-registry=registry-docker-io.kube-system.svc.cluster.local:5000
        resources:
          requests:
            cpu: 6
            memory: 2Gi
